DROP TABLE MOVIE;
DROP TABLE RESERVED;

CREATE TABLE MOVIE(
    SERIAL NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    GENRE VARCHAR2(30) NOT NULL,
    ACCESSAGE NUMBER DEFAULT 0 NOT NULL ,
    TICKET NUMBER DEFAULT 0
);

CREATE TABLE RESERVED(
    SERIAL NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    GENRE VARCHAR2(20) NOT NULL,
    ACCESSAGE NUMBER DEFAULT 0 NOT NULL ,
    TICKET NUMBER DEFAULT 0
);

DROP SEQUENCE SEQ_SERIAL;
CREATE SEQUENCE SEQ_SERIAL
START WITH 1;

INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '인생은 비를 타고', '뮤지컬', 0, 1);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '종결자', '액션', 18, 0);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '언더스탠리', '드라마', 12, 0);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '집토피아', '애니메이션', 0, 3);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '놈의 이름은', '로맨스', 15, 4);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '헬리콥터와 조종사의 돌', '코미디', 12, 4);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '스즈무라의 문따개', '로맨스', 12, 3);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '여우와 탭댄스', '액션', 15, 5);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '괴도 도로롱', '애니메이션', 0, 1);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '화신 : 땅의 길', '액션', 12, 5);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '13일째 금금금', '호러', 15, 5);
INSERT INTO MOVIE VALUES(SEQ_SERIAL.NEXTVAL, '파리의 봄', '드라마', 12, 0);

COMMIT;