--1. 영어영문학과(002) 학생들의 학번, 이름, 입학년도를 입학년도 순으로 조회
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2. 이름이 세 글자가 아닌 교수의 이름, 주민번호 출력
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3. 남성 교수들의 이름, 나이 출력
SELECT PROFESSOR_NAME AS "교수이름", EXTRACT(YEAR FROM SYSDATE) AS "현재연도"
    , 1900 + SUBSTR(PROFESSOR_SSN, 1, 2) AS "출생연도"
    , (EXTRACT(YEAR FROM SYSDATE)
    - (1900 + SUBSTR(PROFESSOR_SSN, 1, 2))) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY "나이";

--4. 교수의 성을 제외한 이름만 출력(성이 2자인 교수는 없다고 가정)
SELECT SUBSTR(PROFESSOR_NAME, 2)
FROM TB_PROFESSOR;

--5. 재수생 입학자(입학 당시 20살 이상인 학생들)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE) - (1900 + SUBSTR(STUDENT_SSN, 1, 2))) >= 20;

--6. 2020년 크리스마스의 요일
SELECT TO_CHAR(TO_DATE(20201225), 'DAY') FROM DUAL;

--7_1. TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD')는 각각 몇년 몇월 몇일?
SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11', 'YY/MM/DD')), 
       EXTRACT(YEAR FROM TO_DATE('49/10/11', 'YY/MM/DD'))
FROM DUAL;
--2099년 10월 11일, 2049년 10월 11일

--7_2. TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')는 각각 몇년 몇월 몇일?
SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11', 'RR/MM/DD')), 
       EXTRACT(YEAR FROM TO_DATE('49/10/11', 'RR/MM/DD'))
FROM DUAL;
--1999년 10월 11일, 2049년 11월 11일

--8. 2000년도 이전 학번인 학생들의 학번, 이름
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

--9. A517178 한아름 학생의 학점 총 평점(소수점 이하 한 자리까지)
SELECT ROUND(AVG(POINT), 1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10. 학과(번호)별 학생 수
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11. 지도 교수를 배정받지 못한 학생의 수
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12. A112113 김고운 학생의 연도 별 평점(소수점 이하 한 자리까지)
SELECT 연도, ROUND(AVG(POINT), 1) AS "연도 별 평점"
FROM(SELECT SUBSTR(TERM_NO, 1, 4) AS "연도" , POINT
     FROM TB_GRADE
     WHERE STUDENT_NO = 'A112113')
GROUP BY 연도
ORDER BY 연도;

--13. 학과별 휴학생 수
SELECT DEPARTMENT_NO AS "학과코드명",
       SUM(DECODE (ABSENCE_YN, 'Y', 1, 'N', 0)) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14. 동명이인 학생 수
SELECT STUDENT_NAME AS "동일이름", COUNT(STUDENT_NAME) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) >= 2
ORDER BY STUDENT_NAME;

--15. A112113 김고운 학생의 학기 별 평점, 연도 별 누적 평점, 총 평점(소수점 1자리까지만 반올림)
--학기 별 평점



SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", SUBSTR(TERM_NO, 5) AS "학기", POINT AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
UNION
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", NVL(NULL, '') AS "학기", ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
UNION ALL
SELECT NVL(NULL, '') AS "년도", NVL(NULL, '') AS "학기", ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';
