--1. TB_CLASS_TYPE에 데이터 입력
INSERT INTO TB_CLASS_TYPE VALUES('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('05', '논문지도');

--2. 일반학생정보 테이블 만들기(서브쿼리 이용)
CREATE TABLE TB_학생일반정보
AS(SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생이름", STUDENT_ADDRESS AS "주소"
    FROM TB_STUDENT);

--3. 국어국문학과 학생 정보 테이블 만들기 
CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생이름",
    (1900 + SUBSTR(STUDENT_SSN, 1, 2)) AS "출생년도",
    PROFESSOR_NAME AS "교수이름"
    FROM TB_STUDENT
    JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
    WHERE DEPARTMENT_NO = 001);

--4.정원 10% 증가(반올림)
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

--5. 주소지 변경
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6. 학생 주민번호 뒷자리 삭제
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

--7. 학점 정정 C3843900 ,A331101
--과목 번호
SELECT CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME = '피부생리학';
--학번
SELECT STUDENT_NO
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE STUDENT_NAME = '김명훈' AND DEPARTMENT_NAME = '의학과';

UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501' AND CLASS_NO = 'C3843900' AND STUDENT_NO = 'A331101';


--8. 휴학생들의 성적 항목 제거
--휴학생들 학번
SELECT STUDENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');
