--1. 학생 이름(오름차순), 주소지
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2. 휴학생 이름 주민번호
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3. 강원도, 경기도에 사는 1900년대 학번 학생들
SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%' AND STUDENT_ADDRESS LIKE '경기도%'
    OR STUDENT_ADDRESS LIKE '강원도%'
ORDER BY STUDENT_NAME;

--4. 법학과 교수 나이순
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '법학과';
-- 법학과 학과코드 = 005

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN;

--5. 2004년 2학기 C3118100 수강생 학점
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO;

--6. 학번, 학생 이름, 학과 이름 (학생 이름 기준 오름차순)
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7. 과목 이름과 과목의 학과 이름 출력
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8. 과목별 교수 이름
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9. 8에서 인문사회 계열만
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE CATEGORY = '인문사회';

--10. 음악학과 학생들의 평점
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '음악학과'; --059

SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", "전체 평점"
FROM (SELECT STUDENT_NO, ROUND(AVG(POINT), 1) AS "전체 평점"
     FROM TB_GRADE
     GROUP BY STUDENT_NO)
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE DEPARTMENT_NO = 059;

--11. 학번 A313047의 학과 이름, 학생 이름, 지도 교수 이름
SELECT DEPARTMENT_NAME AS "학과이름", STUDENT_NAME AS "학생이름"
     , PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12. 2007년 인간관계론 과목을 수강한 학생들
SELECT CLASS_NAME, CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME = '인간관계론'; --C2604100

SELECT STUDENT_NAME, TERM_NO 
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NO = 'C2604100';

--13. 담당교수가 없는 예체능 게열 과목의 이름, 학과
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE PROFESSOR_NO IS NULL AND CATEGORY = '예체능';

--14. 서반아어학과 학생들의 지도교수(없으면 "지도교수 미지정")
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '서반아어학과'; --020

SELECT STUDENT_NAME AS "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
FROM TB_STUDENT
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE TB_STUDENT.DEPARTMENT_NO = '020'
ORDER BY STUDENT_NO;

--15. 휴학생이 아닌 학생 중 평점이 4.0인 학생
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", DEPARTMENT_NAME AS "학과 이름", 평점
FROM (SELECT STUDENT_NO, AVG(POINT) AS "평점"
      FROM TB_GRADE
      GROUP BY STUDENT_NO)
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N' AND 평점 >= 4.0;
-- DEPARTMENT_NAME AS "학과 이름",
--JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
--WHERE ABSENCE_YN = 'N';

--16. 환경조경학과 전공과목들의 과목 별 평점
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '환경조경학과'; --034

SELECT CLASS_NO, CLASS_NAME, "AVG(POINT)"
FROM(SELECT CLASS_NO, AVG(POINT) AS "AVG(POINT)"
    FROM TB_GRADE
    GROUP BY CLASS_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE DEPARTMENT_NO = 034 AND CLASS_TYPE = '전공선택'
ORDER BY CLASS_NO;

--17. 최경희 학생과 같은 과 학생들의 이름과 주소
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');

--18.국어국문학과(001) 총 평점이 가장 높은 학생의 이름과 학번
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, AVG(POINT) AS "AVG(POINT)"
      FROM TB_GRADE
      GROUP BY STUDENT_NO
      ORDER BY AVG(POINT) DESC)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE DEPARTMENT_NO = 001
AND ROWNUM = 1;

--19. 환경조경학과가 속한 계열 학과(자연과학)들의 학과별 전공과목 평점
--GROUP BY DEPARTMENT_NAME
--CATEGORY = '자연과학'
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT), 1)
FROM(SELECT DEPARTMENT_NAME, CATEGORY, CLASS_NO, POINT
     FROM TB_DEPARTMENT
     JOIN TB_CLASS USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(CLASS_NO)
     WHERE CATEGORY = '자연과학')
GROUP BY DEPARTMENT_NAME;


